{
 "title": "Sparkbot Analytics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Websocket Latency",
   "type": "timeseries",
   "description": "Latency to the Discord API web socket",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "SparkbotDB",
     "rawSql": "SELECT latency, timestamp FROM SparkbotDB.analyticslogs "
    }
   ]
  },
  {
   "title": "Users",
   "type": "timeseries",
   "description": "Number of users Sparkbot can currently see in all connected servers",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "SparkbotDB",
     "rawSql": "SELECT user_count, timestamp FROM SparkbotDB.analyticslogs "
    }
   ]
  },
  {
   "title": "Commands Per Hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "SparkbotDB",
     "rawSql": "SELECT \n  $__timeGroupAlias(timestamp, 1h),\n  count(*) as Commands\nFROM SparkbotDB.commandlogs\nWHERE $__timeFilter(timestamp)\nGROUP BY 1\nORDER BY 1; "
    }
   ]
  }
 ]
}